# Generated by Django 2.2.2 on 2019-06-10 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiitem',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='apiitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apiitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='apiitem',
            name='coords',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='apiitem',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='apiitem',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiitem',
            name='mac',
            field=models.CharField(default='', max_length=17),
        ),
        migrations.AddField(
            model_name='apiitem',
            name='presenca',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
