# Generated by Django 2.2.2 on 2019-06-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190610_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiitem',
            name='coords',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='apiitem',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='apiitem',
            name='mac',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='apiitem',
            name='presenca',
            field=models.CharField(max_length=1),
        ),
    ]
